### ISSUE TITLE
Support new DSN format

### ISSUE THREAD

**Issue by vindarel** [mmontone/cl-sentry-client#3]
Hello,

I just created a new project under Sentry, and `initialize-sentry-client` failed on parsing its DSN. 

There is a checkbox on the project settings to "show deprecated DSN", which works.

The new DSN looks like:

    https://7551blahblah6a4foobar121b196@o74423.ingest.sentry.io/6718100

the accepted one:

     https://7551blahblah6a4d97a1foobar21b196:e74b816ac6longkey9c89c54bea@o71542.ingest.sentry.io/5877299

**Comment by mmontone** [comment]
Ok.

I suppose you can use a list as DSN in the meantime:

```
 (list :protocol protocol
            :public-key public-key
            :secret-key secret-key
            :host host
            :project-id project-id
            :uri uri)
```

**Comment by vindarel** [comment]
I can also use the "deprecated DSN" which they still give.

After a quick look we must adapt the regexp and

      (ppcre:register-groups-bind (protocol public-key secret-key host project-id)

where public-key becomes optional. So maybe register-groups-bind isn't adapted anymore.

**Comment by mmontone** [comment]
> I can also use the "deprecated DSN" which they still give.
> 
> After a quick look we must adapt the regexp

yep
